# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b75afd4528164531be204ca868d8658f2df7884d2c3507725071c5f795abcabb7e80854ad70aab1ec94fc326bdaa7bb8b352572ea42d3708411defa5c351ac95

test:
  secret_key_base: 7dfe359a0ef81a08d8876b8b3b7b15016fcfd6a3e4dfb6403a7d330bf885ad164e5d5252d11af85a19f1efcb76903b6ccb904a9e77f3adb22d472db2d73ccff1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 792ea7a7fad4de1ad0682a67e4a5a9d6879a05da96284ce7d7d88d0aa4b377ddaae1696121ee4ba3e215a10094621e8510e95e9c3f37b20f4b39acad92d68fe1
